theme: jekyll-theme-cayman
title: Cristian MartÃ­nez Briones
description: Physicist and Data Scientist 

            ğŸ“ Santiago, Chile | âœ‰ï¸ cristianj3006@gmail.com | ğŸ“± (+569)-77427120
           
